# Netlify Configuration for TaskMate Blog
# Static Next.js Export with /blog basePath

[build]
  command = "npm run build"
  publish = "out"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Blog routing - internal redirects within this site
[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/blog"
  to = "/blog/"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    
# Cache static assets aggressively
[[headers]]
  for = "/blog/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/blog/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML pages with shorter duration
[[headers]]
  for = "/blog/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
